# Generated by Django 3.2 on 2024-12-12 00:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('anios_exp', models.IntegerField()),
                ('campeonatos', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Nombre inválido, solo letras.', regex='^[a-zA-Z ]*$')])),
                ('ciudad', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Ciudad inválida, solo letras.', regex='^[a-zA-Z ]*$')])),
                ('campeonatos', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='El número de campeonatos no puede ser negativo')])),
                ('conferencia', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Conferencia inválida, solo letras.', regex='^[a-zA-Z ]*$')])),
                ('estadio', models.CharField(max_length=100)),
                ('colores', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_nombre', message='Color inválido, solo letras', regex='^[a-zA-Z ]+$')])),
                ('liga', models.CharField(max_length=100)),
                ('director_tecnico', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PruebaApp.directortecnico')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('ppp', models.FloatField()),
                ('eficacia', models.FloatField()),
                ('posicion', models.CharField(choices=[('Base', 'Base'), ('Escolta', 'Escolta'), ('Alero', 'Alero'), ('Ala-Pivot', 'Ala-Pivot'), ('Pivot', 'Pivot')], max_length=20)),
                ('edad', models.IntegerField()),
                ('campeonatos', models.IntegerField()),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PruebaApp.equipo')),
            ],
        ),
    ]
